version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.android.tools.build:gradle
    versions:
    - ">= 4.2.a, < 4.3"
  - dependency-name: com.android.tools.build:gradle
    versions:
    - 7.0.0-alpha05
    - 7.0.0-alpha06
    - 7.0.0-alpha07
    - 7.0.0-alpha08
    - 7.0.0-alpha09
    - 7.0.0-alpha10
    - 7.0.0-alpha11
    - 7.0.0-alpha12
    - 7.0.0-alpha13
  - dependency-name: com.bugsnag:bugsnag-android
    versions:
    - 5.5.2
    - 5.6.0
    - 5.6.2
    - 5.7.0
    - 5.7.1
    - 5.8.0
    - 5.9.0
  - dependency-name: org.jetbrains.kotlin:kotlin-gradle-plugin
    versions:
    - 1.4.21-2
    - 1.4.30
    - 1.4.31
    - 1.4.32
  - dependency-name: com.squareup.leakcanary:plumber-android
    versions:
    - "2.6"
  - dependency-name: com.squareup.leakcanary:leakcanary-android
    versions:
    - "2.6"
  - dependency-name: io.gitlab.arturbosch.detekt:detekt-gradle-plugin
    versions:
    - 1.15.0
