name: Instrumented test workflow

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - release/*

jobs:
  instrumented-tests:
    name: Run tests
    runs-on: macOS-latest
    strategy:
      matrix:
        api-level: [23, 29]
        arch: [x86, x86_64]
        exclude:
          - api-level: 23
            arch: x86_64
          - api-level: 29
            arch: x86
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-
      - uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: ${{ matrix.arch }}
          profile: Nexus 5X
          script: ./gradlew app:connectedMockDebugAndroidTest connectedDebugAndroidTest
        env:
          CI: true
          JAVA_TOOL_OPTIONS: -Xmx3g
          GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2 -Dkotlin.incremental=false -Dkotlin.compiler.execution.strategy=in-process
