name: Instrumented test workflow

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - release/*

jobs:
  instrumented-tests:
    name: Run Instrumented Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Start Android Emulator
        uses: reactivecircus/setup-android-emulator@v0.1.0
        with:
          api-level: 23
      - name: Run Instrumented Tests
        run: ./gradlew connectedCheck
        env:
          JAVA_TOOL_OPTIONS: -Xmx2g
          GRADLE_OPTS: -Dkotlin.incremental=false
